### ISSUE TITLE
scale doesn't work with one arg.

### ISSUE THREAD

**Issue by trusktr** [cssinjs/css-functions#16]
CSS scale accepts either one arg or two args, but the current one here doesn't work with one arg. See MDN [syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scale#Syntax).

If we do `scale(2)` it outputs `"scale(2,)"` with the extra comma, which trips the CSS engine.

**Comment by trusktr** [comment]
I made a PR: https://github.com/cssinjs/css-functions/pull/17

**Comment by HenriBeck** [comment]
Merged. Thanks 👍
